/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oray_sunlogin_servicesdk_jni_ClientServiceSDK */

#ifndef _Included_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
#define _Included_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeLoginWithOpenID
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeLoginWithOpenID
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeLogin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeLogout
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeLogout
  (JNIEnv *, jobject);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeGetAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeGetAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeCreateSession
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeCreateSession
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeDestroySession
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeDestroySession
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeIsLogged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeIsLogged
  (JNIEnv *, jobject);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeIsRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeIsRunning
  (JNIEnv *, jobject);

/*
 * Class:     com_oray_sunlogin_servicesdk_jni_ClientServiceSDK
 * Method:    nativeCreateCxxObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_oray_sunlogin_servicesdk_jni_ClientServiceSDK_nativeCreateCxxObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
